#cloud-config
runcmd:
  - [eval, 'echo $(cat /proc/cmdline) "autoinstall" > /root/cmdline']
  - [eval, 'mount -n --bind -o ro /root/cmdline /proc/cmdline']
  - [eval, 'snap restart subiquity.subiquity-server']
  - [eval, 'snap restart subiquity.subiquity-service']

autoinstall:
  version: 1
  locale: en_US
  identity:
    hostname: <HOSTNAME>
    username: <USERNAME>
    password: <PASSWORD>
  ssh:
    install-server: SSH_INSTALL_SERVER
    authorized-keys:
      - SSH_KEY01
    allow-pw: SSH_ALLOW_PW
  network:
    version: 2
    ethernets:
      NIC_01:
        dhcp4: NIC01_DHCP
        addresses:
          - NIC01_DHCP
        nameservers:
          addresses: [NIC01_DNS01]
      NIC_02:
        dhcp4: NIC02_DHCP
        addresses:
          - NIC02_DHCP
        nameservers:
          addresses: [NIC02_DNS01, NIC02_DNS02]
